/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import ConexaoBanco.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas.A
 */
public class TelaCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    PreparedStatement pst = null;
    Connection con = null;
    ResultSet rs = null;
    
    public TelaCadastroFuncionario() {
        initComponents();
        con = Conexao.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarFuncionario1 = new javax.swing.JButton();
        btnBuscarFuncionario2 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        txtNome3 = new javax.swing.JTextField();
        txtBairro3 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        txtCpf3 = new javax.swing.JTextField();
        txtCidade3 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        txtRg3 = new javax.swing.JTextField();
        comboBoxEstadoCivil3 = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        comboBoxEstado3 = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        txtNumCelular3 = new javax.swing.JTextField();
        txtCep3 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtDataNascimento3 = new javax.swing.JTextField();
        txtEmail3 = new javax.swing.JTextField();
        btnCadastrarFuncionario = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btnBuscarFuncionario = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        comboBoxSexo3 = new javax.swing.JComboBox<>();
        txtEndereco3 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        comboBoxFuncao = new javax.swing.JComboBox<>();
        txtNumEndereco3 = new javax.swing.JTextField();
        labelNome3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIdFuncionario = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("CadastFuncionario");

        btnBuscarFuncionario1.setText("Editar");
        btnBuscarFuncionario1.setPreferredSize(new java.awt.Dimension(82, 32));
        btnBuscarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionario1ActionPerformed(evt);
            }
        });

        btnBuscarFuncionario2.setText("Remover");
        btnBuscarFuncionario2.setPreferredSize(new java.awt.Dimension(82, 32));
        btnBuscarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionario2ActionPerformed(evt);
            }
        });

        jLabel54.setText("Bairro:");

        jLabel55.setText("CPF:");

        jLabel56.setText("Cidade:");

        jLabel57.setText("RG:");

        jLabel47.setText("Esta Civil:");

        comboBoxEstadoCivil3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viuvo(a)" }));

        jLabel58.setText("Estado:");

        comboBoxEstado3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito", "Federal", "Espírito", "Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        jLabel48.setText("Nº Celular:");

        jLabel59.setText("CEP:");

        jLabel60.setText("Nacimento:");

        jLabel49.setText("E-mail:");

        btnCadastrarFuncionario.setText("Cadastra");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel50.setText("Dados Cadastrais");

        jLabel61.setText("Sexo:");

        jLabel51.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel51.setText("Endereço");

        btnBuscarFuncionario.setText("Buscar");
        btnBuscarFuncionario.setPreferredSize(new java.awt.Dimension(82, 32));
        btnBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionarioActionPerformed(evt);
            }
        });

        jLabel52.setText("Endereço:");

        comboBoxSexo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel62.setText("Função:");

        jLabel53.setText("Nº:");

        comboBoxFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Vendedor", "Serviços Gerais" }));

        labelNome3.setText("Nome: ");

        jLabel1.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBairro3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumEndereco3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCep3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnBuscarFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelNome3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNome3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel55)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel57)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRg3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel60)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDataNascimento3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel48)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumCelular3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmail3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel61)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxSexo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel47)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxEstadoCivil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel62)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBoxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(jLabel50)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(txtNumEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56)
                    .addComponent(txtCidade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jLabel59)
                    .addComponent(txtCep3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarFuncionario)
                    .addComponent(btnBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel50)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome3)
                        .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(txtCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel57)
                        .addComponent(txtRg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel60)
                        .addComponent(txtDataNascimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(txtNumCelular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)
                        .addComponent(txtEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboBoxSexo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel61)
                            .addComponent(jLabel47)
                            .addComponent(comboBoxEstadoCivil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62)
                            .addComponent(comboBoxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int validaCamposFuncionario() {

        if (txtNome3.getText().isEmpty() || txtCpf3.getText().isEmpty() || txtRg3.getText().isEmpty() || txtDataNascimento3.getText().isEmpty() || txtNumCelular3.getText().isEmpty() || txtEmail3.getText().isEmpty() || txtEndereco3.getText().isEmpty() || txtNumEndereco3.getText().isEmpty() || txtBairro3.getText().isEmpty() || txtCidade3.getText().isEmpty() || txtCep3.getText().isEmpty()) {
            return 1;
        } else {
            return 2;
        }
    }
    
    public String preenchaCampo()
    {        
        String textPreencha = "Preencha todos os campos para prosseguir.";
        return textPreencha;        
    }
    
     public void cadFuncionario(){        
        if (validaCamposFuncionario() == 2) {
            con = Conexao.conectar();
            String Sql = "INSERT INTO funcionario(nome_funcionario,cpf_funcionario,rg_funcionario,sexo_funcionario,estadocivil_funcionario,datanascimento_funcionario,telefonecelular_funcionario,email_funcionario,especializacao_funcionario,endereco_funcionario,numrua_funcionario,bairro_funcionario,cidade_funcionario,estado_funcionario,cep_funcionario) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            try {
                pst = con.prepareStatement(Sql);
                pst.setString(1, txtNome3.getText());
                pst.setString(2, txtCpf3.getText());
                pst.setString(3, txtRg3.getText());
                pst.setString(4, comboBoxSexo3.getSelectedItem().toString());
                pst.setString(5, comboBoxEstadoCivil3.getSelectedItem().toString());
                pst.setString(6, txtDataNascimento3.getText());
                pst.setString(7, txtNumCelular3.getText());
                pst.setString(8, txtEmail3.getText());
                pst.setString(9, comboBoxFuncao.getSelectedItem().toString());
                pst.setString(10, txtEndereco3.getText());
                pst.setString(11, txtNumEndereco3.getText());
                pst.setString(12, txtBairro3.getText());
                pst.setString(13, txtCidade3.getText());
                pst.setString(14, comboBoxEstado3.getSelectedItem().toString());
                pst.setString(15, txtCep3.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Funcionario cadastrado com sucesso!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro:" + e);
            } finally {
                Conexao.desconectar(con);
            }            
        }else{
            JOptionPane.showMessageDialog(null, preenchaCampo());
        }
    }

    public void busFuncionario() {
        if (txtIdFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Preencha o campo 'ID' com uma id valida.");
        } else {

            con = Conexao.conectar();

            String Sql = "SELECT * FROM funcionario WHERE id_funcionario=?";

            try {
                pst = con.prepareStatement(Sql);
                pst.setString(1, txtIdFuncionario.getText());
                //JOptionPane.showMessageDialog(null, pst);
                rs = pst.executeQuery();

                if (rs.next()) {
                    txtNome3.setText(rs.getString(2));
                    txtCpf3.setText(rs.getString(3));
                    txtRg3.setText(rs.getString(4));
                    comboBoxSexo3.setSelectedItem(rs.getString(5));
                    comboBoxEstadoCivil3.setSelectedItem(rs.getString(6));
                    txtDataNascimento3.setText(rs.getString(7));
                    txtNumCelular3.setText(rs.getString(8));
                    txtEmail3.setText(rs.getString(9));
                    comboBoxFuncao.setSelectedItem(rs.getString(10));
                    txtEndereco3.setText(rs.getString(11));
                    txtNumEndereco3.setText(rs.getString(12));
                    txtBairro3.setText(rs.getString(13));
                    txtCidade3.setText(rs.getString(14));
                    comboBoxEstado3.setSelectedItem(rs.getString(15));
                    txtCep3.setText(rs.getString(16));
                    JOptionPane.showMessageDialog(null, "Funcionario localizado com sucesso!");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro:" + e);
            } finally {
                Conexao.desconectar(con);
            }
        }
    }
    
    public void updateFuncionario() {
        
        if (validaCamposFuncionario() == 2){
            con = Conexao.conectar();

            String Sql = "UPDATE funcionario SET nome_funcionario=?,cpf_funcionario=?,rg_funcionario=?,sexo_funcionario=?,estadocivil_funcionario=?,datanascimento_funcionario=?,telefonecelular_funcionario=?,email_funcionario=?,endereco_funcionario=?,numrua_funcionario=?,bairro_funcionario=?,cidade_funcionario=?,estado_funcionario=?,cep_funcionario=? WHERE id_funcionario=?";

            try {
                pst = con.prepareStatement(Sql);
                pst.setString(1, txtNome3.getText());
                pst.setString(2, txtCpf3.getText());
                pst.setString(3, txtRg3.getText());
                pst.setString(4, comboBoxSexo3.getSelectedItem().toString());
                pst.setString(5, comboBoxEstadoCivil3.getSelectedItem().toString());
                pst.setString(6, txtDataNascimento3.getText());
                pst.setString(7, txtNumCelular3.getText());
                pst.setString(8, txtEmail3.getText());
                pst.setString(9, txtEndereco3.getText());
                pst.setString(10, txtNumEndereco3.getText());
                pst.setString(11, txtBairro3.getText());
                pst.setString(12, txtCidade3.getText());
                pst.setString(13, comboBoxEstado3.getSelectedItem().toString());
                pst.setString(14, txtCep3.getText());
                pst.setString(15, txtIdFuncionario.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Funcionario atualizado com sucesso!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro:" + e);

            } finally {
                Conexao.desconectar(con);
            }
        } else {
            JOptionPane.showMessageDialog(null, preenchaCampo());
        }

    }
    
    public void deleteFuncionario(){        
        if (txtIdFuncionario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Preencha o campo 'ID' com uma id valida.");                        
        }else{            
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente remover esse usuario?", title, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                //Usuário clicou em Sim. Executar o código correspondente.
                JOptionPane.showMessageDialog(null, "Ok, você sabe o que faz.");
                con = Conexao.conectar();
                String Sql = "DELETE FROM funcionario WHERE id_funcionario=?";
                try {
                    pst = con.prepareStatement(Sql);
                    pst.setString(1, txtIdFuncionario.getText());
                    pst.execute();

                    JOptionPane.showMessageDialog(null, "Funcionario removido com sucesso!");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro:" + e);

                } finally {
                    Conexao.desconectar(con);
                }

            } else if (resposta == JOptionPane.NO_OPTION) {
                //Usuário clicou em não. Executar o código correspondente.
            }
        }    
    }
    
    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        cadFuncionario();
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionarioActionPerformed
        // TODO add your handling code here:   
        busFuncionario();
    }//GEN-LAST:event_btnBuscarFuncionarioActionPerformed

    private void btnBuscarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionario1ActionPerformed
        // TODO add your handling code here:
        updateFuncionario();
    }//GEN-LAST:event_btnBuscarFuncionario1ActionPerformed

    private void btnBuscarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionario2ActionPerformed
        // TODO add your handling code here:
        deleteFuncionario();
    }//GEN-LAST:event_btnBuscarFuncionario2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarFuncionario;
    private javax.swing.JButton btnBuscarFuncionario1;
    private javax.swing.JButton btnBuscarFuncionario2;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JComboBox<String> comboBoxEstado3;
    private javax.swing.JComboBox<String> comboBoxEstadoCivil3;
    private javax.swing.JComboBox<String> comboBoxFuncao;
    private javax.swing.JComboBox<String> comboBoxSexo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel labelNome3;
    private javax.swing.JTextField txtBairro3;
    private javax.swing.JTextField txtCep3;
    private javax.swing.JTextField txtCidade3;
    private javax.swing.JTextField txtCpf3;
    private javax.swing.JTextField txtDataNascimento3;
    private javax.swing.JTextField txtEmail3;
    private javax.swing.JTextField txtEndereco3;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtNome3;
    private javax.swing.JTextField txtNumCelular3;
    private javax.swing.JTextField txtNumEndereco3;
    private javax.swing.JTextField txtRg3;
    // End of variables declaration//GEN-END:variables
}
